repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.2
  hooks:
  - id: markdownlint

repos:
- repo: https://github.com/tcort/markdown-link-check
  rev: v3.10.3
  hooks:
  - id: markdown-link-check