name: Check Markdown links for modified files

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: 'mlc_config.json'
        check-modified-files-only: 'yes'
        use-verbose-mode: 'yes'
        base-branch: 'main'