name: Manual Markdown links for all files

on: [workflow_dispatch]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: 'mlc_pull_req_config.json'
        use-verbose-mode: 'yes'
        base-branch: 'main'
        